version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/todos
    depends_on:
      - mongo
    networks:
      - todo-network

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mongo-data:
