name: Deploy Node.js API

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug EC2_HOST value
        run: echo "Connecting to ${{ secrets.EC2_HOST }}"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $(echo "${{ secrets.EC2_HOST }}" | cut -d'@' -f2) >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          rsync -avz --exclude='.git' -e "ssh -i ~/.ssh/id_ed25519" . ${{ secrets.EC2_HOST }}:~/app
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app
            docker-compose down || true
            docker-compose up -d --build
          EOF
